/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Sun Feb 28 22:39:26 2016. */

#include "ArduTank.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SetSpeedCommand_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetSpeedCommand, speed, speed, 0),
    PB_LAST_FIELD
};

const pb_field_t MoveCommand_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, MoveCommand, direction, direction, 0),
    PB_LAST_FIELD
};

const pb_field_t StopCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t GetVersionCommand_fields[1] = {
    PB_LAST_FIELD
};

const pb_field_t ArduTankCommand_fields[5] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, ArduTankCommand, GetVersionValue, GetVersionValue, &GetVersionCommand_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, ArduTankCommand, SetSpeedCommandValue, GetVersionValue, &SetSpeedCommand_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, ArduTankCommand, MoveCommandValue, SetSpeedCommandValue, &MoveCommand_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, ArduTankCommand, StopCommandValue, MoveCommandValue, &StopCommand_fields),
    PB_LAST_FIELD
};

const pb_field_t GetVersionResponse_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, GetVersionResponse, major, major, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, GetVersionResponse, minor, major, 0),
    PB_LAST_FIELD
};

const pb_field_t ArduTankResponse_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, ArduTankResponse, GetVersionResponseValue, GetVersionResponseValue, &GetVersionResponse_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ArduTankCommand, GetVersionValue) < 65536 && pb_membersize(ArduTankCommand, SetSpeedCommandValue) < 65536 && pb_membersize(ArduTankCommand, MoveCommandValue) < 65536 && pb_membersize(ArduTankCommand, StopCommandValue) < 65536 && pb_membersize(ArduTankResponse, GetVersionResponseValue) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SetSpeedCommand_MoveCommand_StopCommand_GetVersionCommand_ArduTankCommand_GetVersionResponse_ArduTankResponse)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ArduTankCommand, GetVersionValue) < 256 && pb_membersize(ArduTankCommand, SetSpeedCommandValue) < 256 && pb_membersize(ArduTankCommand, MoveCommandValue) < 256 && pb_membersize(ArduTankCommand, StopCommandValue) < 256 && pb_membersize(ArduTankResponse, GetVersionResponseValue) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SetSpeedCommand_MoveCommand_StopCommand_GetVersionCommand_ArduTankCommand_GetVersionResponse_ArduTankResponse)
#endif


/* @@protoc_insertion_point(eof) */
